2025-03-14 18:02:59,084 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:07:12,615 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:10:04,280 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:15:02,547 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:15:06,298 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:15:07,863 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:21:52,297 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:23:29,764 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:29:23,804 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-14 18:37:20,607 | ERROR | produto_routes | Erro ao adicionar produto: Erro ao tentar adicionar produto
2025-03-15 10:50:00,266 | ERROR | produto_routes | Erro inesperado ao adicionar produto: Erro ao tentar adicionar produto
2025-03-17 18:39:10,067 | ERROR | route_auth | Erro inesperado no login: type object 'UtilizadorService' has no attribute 'buscar_por_email'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.buscar_por_email(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UtilizadorService' has no attribute 'buscar_por_email'
2025-03-17 18:40:33,875 | ERROR | route_auth | Erro inesperado no login: type object 'UtilizadorService' has no attribute 'buscar_por_email'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.buscar_por_email(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UtilizadorService' has no attribute 'buscar_por_email'
2025-03-17 18:42:34,277 | ERROR | route_auth | Erro inesperado no login: type object 'UtilizadorService' has no attribute 'buscar_por_email'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.buscar_por_email(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UtilizadorService' has no attribute 'buscar_por_email'
2025-03-17 18:42:39,446 | ERROR | route_auth | Erro inesperado no login: type object 'UtilizadorService' has no attribute 'buscar_por_email'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.buscar_por_email(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'UtilizadorService' has no attribute 'buscar_por_email'
2025-03-17 18:43:43,069 | ERROR | route_auth | Erro inesperado no login: UtilizadorService.autenticar() missing 1 required positional argument: 'password'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UtilizadorService.autenticar() missing 1 required positional argument: 'password'
2025-03-17 18:43:46,051 | ERROR | route_auth | Erro inesperado no login: UtilizadorService.autenticar() missing 1 required positional argument: 'password'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get("email"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: UtilizadorService.autenticar() missing 1 required positional argument: 'password'
2025-03-17 18:44:18,830 | ERROR | route_auth | Erro inesperado no login: type object 'AuthService' has no attribute 'gerar_token'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get("email"),data.get("password"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\utilizadoresmanager.py", line 23, in autenticar
    return AuthService.gerar_token({"email": utilizador.email, "role": utilizador.role})
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AuthService' has no attribute 'gerar_token'. Did you mean: 'gerar_tokens'?
2025-03-17 18:44:20,742 | ERROR | route_auth | Erro inesperado no login: type object 'AuthService' has no attribute 'gerar_token'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get("email"),data.get("password"))
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\services\utilizadoresmanager.py", line 23, in autenticar
    return AuthService.gerar_token({"email": utilizador.email, "role": utilizador.role})
           ^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'AuthService' has no attribute 'gerar_token'. Did you mean: 'gerar_tokens'?
2025-03-17 18:45:06,533 | ERROR | route_auth | Erro inesperado no login: 'builtin_function_or_method' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get["email"],data.get["password"])
                                              ~~~~~~~~^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
2025-03-17 18:45:07,962 | ERROR | route_auth | Erro inesperado no login: 'builtin_function_or_method' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 21, in login
    utilizador = UtilizadorService.autenticar(data.get["email"],data.get["password"])
                                              ~~~~~~~~^^^^^^^^^
TypeError: 'builtin_function_or_method' object is not subscriptable
2025-03-17 18:48:07,718 | ERROR | route_auth | Erro inesperado no login: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 27, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 18, in gerar_tokens
    access_token = jwt.encode(
                   ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-03-17 18:48:10,196 | ERROR | route_auth | Erro inesperado no login: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 27, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 18, in gerar_tokens
    access_token = jwt.encode(
                   ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-03-17 18:49:40,532 | ERROR | route_auth | Erro inesperado no login: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 28, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 18, in gerar_tokens
    access_token = jwt.encode(
                   ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-03-17 18:49:49,790 | ERROR | route_auth | Erro inesperado no login: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 28, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 18, in gerar_tokens
    access_token = jwt.encode(
                   ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-03-17 18:52:19,451 | ERROR | route_auth | Erro inesperado no login: module 'jwt' has no attribute 'encode'
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 28, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 18, in gerar_tokens
    access_token = jwt.encode(
                   ^^^^^^^^^^
AttributeError: module 'jwt' has no attribute 'encode'
2025-03-17 19:03:39,658 | ERROR | route_auth | Erro inesperado no login: 'Utilizador' object is not subscriptable
Traceback (most recent call last):
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\routes\api\auth.py", line 27, in login
    access_token, refresh_token = AuthService.gerar_tokens(utilizador)
                                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tutas\Documents\Projetos GitHUB\store-management-system\util\auth.py", line 20, in gerar_tokens
    "id": utilizador["id"],
          ~~~~~~~~~~^^^^^^
TypeError: 'Utilizador' object is not subscriptable
